### ISSUE TITLE
Highlight and moving mouse to edges doesnt scroll

### ISSUE THREAD

**Issue by Noitidart** [tronghiep92/perfect-scrollbar-react#1]
When trying to highlight text, it does not autoscroll when mouse moves to scrollable edge. Is it possible to get support for this?

**Comment by nghiepdev** [comment]
@Noitidart This is a problem of [perfect-scrollbar](https://github.com/utatti/perfect-scrollbar) and some issues another to it.
I recommended use [smooth-scrollbar-react](https://github.com/nghiepit/smooth-scrollbar-react)

**Comment by Noitidart** [comment]
Is there no plan to be fixed?
