### ISSUE TITLE
z-index problem with my custom Dropdown

### ISSUE THREAD

**Issue by vijayst** [tronghiep92/perfect-scrollbar-react#2]
I have a z-index problem with my custom Dropdown. Dropdown uses perfect-scrollbar-react to provide a custom scrollbar. When the dropdown opens, it is alright. But when I start scrolling, the new content seems to lose its z-index. [CodeSandbox Demo](https://codesandbox.io/s/r7y7107npm)

**Comment by nghiepdev** [comment]
@vijayst You just need to add
```css
.menu .menu-item {
  background: white;
}
```

**Comment by vijayst** [comment]
Thanks, that worked.
